repos:
  - repo: local
    hooks:
      - id: cljstyle
        name: cljstyle
        entry: bin/cljstyle fix
        language: system
        types: [file]
        files: \.(clj[csx]?|edn)$
      - id: prettier
        name: prettier
        language: docker_image
        entry: tmknom/prettier
        types: [text]
        args: [--write, --list-different, --ignore-unknown]
  - repo: https://github.com/clj-kondo/clj-kondo
    rev: v2023.10.20
    hooks:
      - id: clj-kondo-docker
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4
    hooks:
      - id: shfmt-docker
        args: [-w, -s, -i, "2"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
