exclude: ^vendor/
repos:
  - repo: https://github.com/clj-kondo/clj-kondo
    rev: v2023.10.20
    hooks:
      - id: clj-kondo-docker
        args: [clj-kondo, --lint, src, test]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4
    hooks:
      - id: shfmt-docker
        entry: mvdan/shfmt:v3.7.0
        args: [-w, -s, -i, "2"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: cljstyle
        name: cljstyle
        entry: bin/_cljstyle fix
        language: system
        types: [file]
      - id: prettier
        name: prettier
        language: docker_image
        entry: tmknom/prettier
        types: [text]
        args: [--write, --list-different, --ignore-unknown]
      - id: git-diff
        name: git-diff
        language: system
        entry: git --no-pager diff --color --exit-code
        always_run: true
