name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Clojure
        working-directory: /tmp
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
          chmod +x posix-install.sh
          sudo ./posix-install.sh
          rm posix-install.sh
      - name: Install Clojure deps
        run: bin/install-deps
      - name: npm install
        run: npm install
      - name: Install pre-commit
        run: pip3 install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Run clj tests
        run: bin/run-tests clj
      - name: Run cljs tests
        run: bin/run-tests cljs
