name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v4
        name: Set up Node
        with:
          node-version-file: .node-version
          cache: npm
      - uses: actions/setup-java@v4
        name: Set up Java
        with:
          distribution: temurin
          java-version-file: .java-version
          cache: maven
          cache-dependency-path: deps.edn
      - name: Add Homebrew to path
        run: echo /home/linuxbrew/.linuxbrew/bin >> "$GITHUB_PATH"
      - name: Install Homebrew
        run: bin/ci/install-homebrew
      - name: Calculate Homebrew formula versions hash
        id: formulae-hash
        run: echo "result=$(bin/ci/formulae-hash)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        name: Homebrew cache
        with:
          path: /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-homebrew-${{ hashFiles('Brewfile') }}-${{ steps.formulae-hash.outputs.result }}
      - uses: actions/cache@v3
        name: pre-commit cache
        with:
          path: /home/runner/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/cache@v3
        name: .gitlibs cache
        with:
          path: /home/runner/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('deps.edn') }}
      - name: Install dependencies
        run: |
          touch /tmp/brew-bundle-github-actions
          bin/install-deps
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Run clj tests
        run: bin/run-tests clj
      - name: Run cljs tests
        run: bin/run-tests cljs
