name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v4
        name: Set up Node
        with:
          node-version: lts/*
          cache: npm
      - uses: actions/setup-java@v4
        name: Set up Java
        with:
          distribution: temurin
          java-version: 11
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: 3.12
          cache: pip
      - uses: actions/cache@v3
        name: pre-commit cache
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Docker cache
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/cache@v3
        name: Clojure cache
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
      - name: Install Clojure
        run: |
          cd /tmp
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
          chmod +x posix-install.sh
          sudo ./posix-install.sh
      - name: Install cljstyle
        run: |
          cd /tmp
          curl -sLO https://raw.githubusercontent.com/greglook/cljstyle/main/script/install-cljstyle
          chmod +x install-cljstyle
          sudo ./install-cljstyle
      - name: Run pre-commit hooks
        run: |
          pip install -r requirements.txt
          pre-commit run --all-files
      - name: Run clj tests
        run: bin/test clj
      - name: Run cljs tests
        run: |
          npm install
          bin/test cljs
